### ISSUE TITLE
Incorrect viewport meta tags messes up  IOS  native deployment

### ISSUE THREAD

**Issue by aaronksaunders** [danielroe/nuxt-ionic#15]
### 🐛 The bug

You can only see the issue on the device, but it appears that the ios specific styling is not coming across in the build. 

I took your sample playground code and deployed it to the device and this is what it looks like. it looks the way it should on Android

I spent the day trying to edit the module, but I am new to Nuxt modules so i am moving along slowly

<img width="518" alt="Screen Shot 2022-06-23 at 3 53 02 PM" src="https://user-images.githubusercontent.com/524953/175393928-55ab54f7-eae3-42a6-99bf-192d6bcab180.png">

### 🛠️ To reproduce

https://github.com/aaronksaunders/ionic-nuxt-playground

### 🌈 Expected behaviour

for app to render appropriately on device

**Comment by aaronksaunders** [comment]
the error is here - https://github.com/danielroe/nuxt-ionic/blob/020fff23d6b36f37d9c14cbd5e850e925b3472f2/src/parts/meta.ts#L18

i would try and submit a PR but not sure I understand everything going on in the build process to be able to write a test to verify the change

```
  nuxt.options.app.head.viewport =
    'viewport-fit: cover, width: device-width, initial-scale: 1.0, minimum-scale: 1.0, maximum-scale: 1.0, user-scalable: no'
```
should be

```
  nuxt.options.app.head.viewport =
    'viewport-fit=cover, width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no'
```

**Comment by sethjfischer** [comment]
Unless the ionic module overrides this... you could adjust the nuxt config to override the meta options when you generate:
`  app: {
    head: {
      meta: [
        { name: 'viewport', content: 'width=device-width, user-scalable=no, viewport-fit=cover' },
      ],
    },
  },`
