### ISSUE TITLE
Middleware Doesnt Seem To Work With Nuxt Ionic

### ISSUE THREAD

**Issue by aaronksaunders** [danielroe/nuxt-ionic#19]
### 🐛 The bug

middleware is not being called

### 🛠️ To reproduce
1) go to tab 3
2) click the button
3) middle ware should redirect to index

https://stackblitz.com/edit/github-jxba2j?file=pages/tabs/tab3.vue

### 🌈 Expected behaviour

middleware to be called

**Comment by aaronksaunders** [comment]
this bug has been here for a while, if there is an alternate way to create navigation guards without using middleware can someone please suggest otherwise how to I create an app that requires authentication with this nuxt-ionc module?

**Comment by daver987** [comment]
This also was my biggest issue with this module.  This module actually makes working with ionic fun instead of cumbersome. Once this get's resolved it's gonna be amazing!

**Comment by aaronksaunders** [comment]
@daver987 I solved my issue by using [ionic's LifeCycle methods](https://ionicframework.com/docs/vue/lifecycle). I wanted to use middleware for authentication, but now I just check in ionViewWillEnter

**Comment by daver987** [comment]
I will have to check that out!  Thank you for the tip.  :)

On Sep 4, 2022, at 10:42 PM, Aaron K Saunders ***@***.******@***.***>> wrote:



@daver987<https://github.com/daver987> I solved my issue by using ionic's LifeCycle methods<https://ionicframework.com/docs/vue/lifecycle>. I wanted to use middleware for authentication, but now I just check in ionViewWillEnter
