### ISSUE TITLE
feat: ionic animation component

### ISSUE THREAD

**Issue by Lexpeartha** [danielroe/nuxt-ionic#34]
### 🆒 Your use case

Ionic recommends usage of it's own utilities for animations for inclusive platform compatibility and making sure custom animations don't interfere with route popping/pushing animations, so it would be convenient if `nuxt-ionic` could provide a component that will easily handle all this

Check official docs [here](https://ionicframework.com/docs/utilities/animations)

### 🆕 The solution you'd like

Ionic team already made something similar for react, and it could be a decent starting point:
```jsx
<CreateAnimation
  duration={1000}
  fromTo={{
    property: 'opacity',
    fromValue: '1',
    toValue: '0.5'
  }}
>
...
</CreateAnimation>
```
Specific props and their handling is up to debate, but I reckon something like this could work

### ℹ️ Additional info

Would be more than happy to work on a PR if I receive a green light 😄

**Comment by danielroe** [comment]
Sounds nice to me! Would be worth looking into how/whether to integrate with the [native `Transition` element from Vue](https://vuejs.org/guide/built-ins/transition.html). We will also need to turn off `pageTransition` and `layoutTransition` within the Nuxt pages integration - see https://github.com/nuxt/framework/issues/5729 which will make this easier.

**Comment by Lexpeartha** [comment]
Hm, based on documentation I think this implementation was made as replacement for `Transition`, assuming based on docs:
> Ionic Animations uses the [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) to build and run your animations. In doing this, we offload all work required to compute and run your animations to the browser. As a result, this allows the browser to make any optimizations it needs and ensures your animations run as smoothly as possible. While most browsers support a basic implementation of Web Animations, we fallback to [CSS Animations](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations) for browsers that do not support Web Animations. The performance difference in switching between these two should typically be negligible.

Also in vue examples they are passing element ref to the animation function, so I don't think there's space for native `Transition` component in here. However managing page and layout transition with custom component certainly sounds interesting!

**Comment by Lexpeartha** [comment]
Made component that should be very similar to React's implementation. But I would appreciate feddback

Also it can still use some improvements, for example it could have `playOnVisible` and play it only when intersection observer tells that element is on screen
