### ISSUE TITLE
help: Not working

### ISSUE THREAD

**Issue by R0N1n-dev** [danielroe/nuxt-ionic#4]
### 📚 What are you trying to do?

Get running with OptionsAPI

### 🔍 What have you tried?

Docs? Yes.
Only in CompositionAPI and Typescript

repo: 
R0N1n-dev/nuxtonic

**Comment by danielroe** [comment]
You won't be able to use composables within mounted. In the example you give, you can just rename it to setup and you should be good to go.

```diff
 export default {
-  async mounted(){
+  async setup(){
     await useIonRouter.push("/home")
     }
 };
```

You can find out more about composables here: https://vuejs.org/guide/reusability/composables.html#composables

For more about how to use Ionic without composables, you had best check out their documentation: https://ionicframework.com/docs/vue/overview

**Comment by R0N1n-dev** [comment]
The above advice did not work BTW.

**Comment by danielroe** [comment]
Oops, you're right - it should be:

```js
    const router = useIonRouter()
    await router.push("/home")
```

Here you go: https://stackblitz.com/edit/github-fbm9xw

**Comment by danielroe** [comment]
Seems to work fine for me: https://stackblitz.com/edit/github-fbm9xw.

**Comment by R0N1n-dev** [comment]
I swear this is not working.
😑

**Comment by danielroe** [comment]
Can you describe what isn't working? See my stackblitz link above.

**Comment by R0N1n-dev** [comment]
I get this error in the browser console and an empty white screen

GET http://localhost:3000/_nuxt/node_modules/.vite/deps/vue.js?v=56e41e9b net::ERR_ABORTED 504 (Gateway Timeout)      on entry.mjs

**Comment by danielroe** [comment]
Hm. That looks like maybe you have a service worker registered on that port? Or another server running? But it doesn't seem to be related to this project.

Would you try opening in an incognito tab?

**Comment by R0N1n-dev** [comment]
Thought so too and so I unregistered all my service workers. Nothing.
Still don't work

**Comment by R0N1n-dev** [comment]
Problem was a service worker that seemed to be served as soon as I tried to 
access the address in the browser.
Don't know how it came up, but I had been working with PWAS of late.
Anyway, it works now. Looking forward to it's development

**Comment by danielroe** [comment]
Glad you could resolve it!
