### ISSUE TITLE
IonBackdrop doesn't load its style if used on app.vue

### ISSUE THREAD

**Issue by Kapcash** [danielroe/nuxt-ionic#52]
### 🐛 The bug

I want to use `ion-menu` on my app, and this component is supposed to sit next to `ion-router-outlet`. So I overrided my `app.vue` to include this in the template.

But apparently, it doesn't load the ionic component's styles properly, because the `ion-backdrop` (a child component of `ion-menu`) now displays above all components and make the app unclickable.

Note: if I move the `ion-menu` component inside a page instead of the `app.vue`, the styles are correctly loaded.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-fcrwqw?file=pages/index.vue

### 🌈 Expected behaviour

I expect Ionic components to properly load there css style even when used from `app.vue`.

**Comment by aaronksaunders** [comment]
i have an ion-menu working fine with this module, you can checkout what I did here
https://stackblitz.com/edit/nuxt-starter-rqvhxt?file=README.md
