### ISSUE TITLE
type error on built-in ionic components (`property 'modelValue' is missing in type '{}'`)

### ISSUE THREAD

**Issue by aaronksaunders** [danielroe/nuxt-ionic#9]
### 📚 What are you trying to do?

<img width="989" alt="Screen Shot 2022-06-21 at 12 51 15 AM" src="https://user-images.githubusercontent.com/524953/174718754-22afe3ab-bcbb-4f6e-990d-d5c320509c99.png">

Getting errors around the Ionic Components that were auto imported

**Comment by danielroe** [comment]
The components are recognised, but the types aren't exactly right within Ionic itself.

This is the upstream issue to follow: https://github.com/ionic-team/ionic-framework/issues/24169

**Comment by aaronksaunders** [comment]
what is interesting is that I only get this issue when the components are preloaded, when loading the components in the actual component I get no errors and it seems to work fine.

**Comment by danielroe** [comment]
I still experience it when disabling the auto-imports and manually importing in script setup.

**Comment by aaronksaunders** [comment]
https://github.com/aaronksaunders/ionic-capacitor-nuxt-video-app
this is my project I created a few weeks ago that I just checked and there are no issues as you can see from the screen shot below.

running in the same visual studio code and there are no issues

<img width="1089" alt="Screen Shot 2022-06-21 at 5 20 33 PM" src="https://user-images.githubusercontent.com/524953/174899291-baa3c1c2-e4b3-4bfc-a4f8-e70c99c82780.png">

**Comment by danielroe** [comment]
Checking your project and adding the current version of `@ionic/vue`, I get the same errors. (As the issue I linked above indicates, the issue is upstream and not with `nuxt-ionic`.

![CleanShot 2022-06-21 at 22 35 21](https://user-images.githubusercontent.com/28706372/174901254-963d13b5-1a39-42ab-bc40-16fcefa5b066.png)

**Comment by aaronksaunders** [comment]
ok... I am not trying to be difficult, I am just saying that there is an issue and I am trying to get to bottom of it, I use Ionic, with vue on multiple projects and I don't have this problem... 

What you have here is pretty awesome and I think people will find it beneficial but not with that error.

I have made a video about using Ionic with Nuxt and nowhere in the video do I run into this problem.
https://www.loom.com/share/d13678c6bcd145b7a18cdc60cf9e56bf

I will keep at it and let you know if I find out what the issue is

**Comment by aaronksaunders** [comment]
I played around with the version numbers as you suggested and you are correct that is what the issue is. Thanks for sticking with me through this. As I said, I think this is pretty awesome, and looking forward to creating some content around this
